using System;
using System.Collections.Generic;
using System.Linq;
using MyCountry.Models;

namespace MyCountry.Repository
{
    public interface IDistrictRepository
    {
        List<District> GetAll();
    }

    public class DistrictRepository : IDistrictRepository
    {
        private List<District> _districts;

        public DistrictRepository()
        {
            InitData();
        }

        public List<District> GetAll()
        {
            return _districts;
        }

        public District GetByCode(string code)
        {
            return _districts.FirstOrDefault(x=> x.Code == code);

            //foreach (var district in _districts)
            //{
            //    if(district.Code == code)
            //    {
            //        return district;
            //    }
            //}

            //return null;
        }

        private void InitData()
        {
            _districts =  new List<District>
            {
                new District("001", "Quận Ba Đình", "Quận", "01"),
                new District("002", "Quận Hoàn Kiếm", "Quận", "01"),
                new District("003", "Quận Tây Hồ", "Quận", "01"),
                new District("004", "Quận Long Biên", "Quận", "01"),
                new District("005", "Quận Cầu Giấy", "Quận", "01"),
                new District("006", "Quận Đống Đa", "Quận", "01"),
                new District("007", "Quận Hai Bà Trưng", "Quận", "01"),
                new District("008", "Quận Hoàng Mai", "Quận", "01"),
                new District("009", "Quận Thanh Xuân", "Quận", "01"),
                new District("016", "Huyện Sóc Sơn", "Huyện", "01"),
                new District("017", "Huyện Đông Anh", "Huyện", "01"),
                new District("018", "Huyện Gia Lâm", "Huyện", "01"),
                new District("019", "Quận Nam Từ Liêm", "Quận", "01"),
                new District("020", "Huyện Thanh Trì", "Huyện", "01"),
                new District("021", "Quận Bắc Từ Liêm", "Quận", "01"),
                new District("024", "Thành phố Hà Giang", "Thành phố", "02"),
                new District("026", "Huyện Đồng Văn", "Huyện", "02"),
                new District("027", "Huyện Mèo Vạc", "Huyện", "02"),
                new District("028", "Huyện Yên Minh", "Huyện", "02"),
                new District("029", "Huyện Quản Bạ", "Huyện", "02"),
                new District("030", "Huyện Vị Xuyên", "Huyện", "02"),
                new District("031", "Huyện Bắc Mê", "Huyện", "02"),
                new District("032", "Huyện Hoàng Su Phì", "Huyện", "02"),
                new District("033", "Huyện Xín Mần", "Huyện", "02"),
                new District("034", "Huyện Bắc Quang", "Huyện", "02"),
                new District("035", "Huyện Quang Bình", "Huyện", "02"),
                new District("040", "Thành phố Cao Bằng", "Thành phố", "04"),
                new District("042", "Huyện Bảo Lâm", "Huyện", "04"),
                new District("043", "Huyện Bảo Lạc", "Huyện", "04"),
                new District("044", "Huyện Thông Nông", "Huyện", "04"),
                new District("045", "Huyện Hà Quảng", "Huyện", "04"),
                new District("046", "Huyện Trà Lĩnh", "Huyện", "04"),
                new District("047", "Huyện Trùng Khánh", "Huyện", "04"),
                new District("048", "Huyện Hạ Lang", "Huyện", "04"),
                new District("049", "Huyện Quảng Uyên", "Huyện", "04"),
                new District("050", "Huyện Phục Hoà", "Huyện", "04"),
                new District("051", "Huyện Hoà An", "Huyện", "04"),
                new District("052", "Huyện Nguyên Bình", "Huyện", "04"),
                new District("053", "Huyện Thạch An", "Huyện", "04"),
                new District("058", "Thành Phố Bắc Kạn", "Thành phố", "06"),
                new District("060", "Huyện Pác Nặm", "Huyện", "06"),
                new District("061", "Huyện Ba Bể", "Huyện", "06"),
                new District("062", "Huyện Ngân Sơn", "Huyện", "06"),
                new District("063", "Huyện Bạch Thông", "Huyện", "06"),
                new District("064", "Huyện Chợ Đồn", "Huyện", "06"),
                new District("065", "Huyện Chợ Mới", "Huyện", "06"),
                new District("066", "Huyện Na Rì", "Huyện", "06"),
                new District("070", "Thành phố Tuyên Quang", "Thành phố", "08"),
                new District("071", "Huyện Lâm Bình", "Huyện", "08"),
                new District("072", "Huyện Nà Hang", "Huyện", "08"),
                new District("073", "Huyện Chiêm Hóa", "Huyện", "08"),
                new District("074", "Huyện Hàm Yên", "Huyện", "08"),
                new District("075", "Huyện Yên Sơn", "Huyện", "08"),
                new District("076", "Huyện Sơn Dương", "Huyện", "08"),
                new District("080", "Thành phố Lào Cai", "Thành phố", "10"),
                new District("082", "Huyện Bát Xát", "Huyện", "10"),
                new District("083", "Huyện Mường Khương", "Huyện", "10"),
                new District("084", "Huyện Si Ma Cai", "Huyện", "10"),
                new District("085", "Huyện Bắc Hà", "Huyện", "10"),
                new District("086", "Huyện Bảo Thắng", "Huyện", "10"),
                new District("087", "Huyện Bảo Yên", "Huyện", "10"),
                new District("088", "Huyện Sa Pa", "Huyện", "10"),
                new District("089", "Huyện Văn Bàn", "Huyện", "10"),
                new District("094", "Thành phố Điện Biên Phủ", "Thành phố", "11"),
                new District("095", "Thị Xã Mường Lay", "Thị xã", "11"),
                new District("096", "Huyện Mường Nhé", "Huyện", "11"),
                new District("097", "Huyện Mường Chà", "Huyện", "11"),
                new District("098", "Huyện Tủa Chùa", "Huyện", "11"),
                new District("099", "Huyện Tuần Giáo", "Huyện", "11"),
                new District("100", "Huyện Điện Biên", "Huyện", "11"),
                new District("101", "Huyện Điện Biên Đông", "Huyện", "11"),
                new District("102", "Huyện Mường Ảng", "Huyện", "11"),
                new District("103", "Huyện Nậm Pồ", "Huyện", "11"),
                new District("105", "Thành phố Lai Châu", "Thành phố", "12"),
                new District("106", "Huyện Tam Đường", "Huyện", "12"),
                new District("107", "Huyện Mường Tè", "Huyện", "12"),
                new District("108", "Huyện Sìn Hồ", "Huyện", "12"),
                new District("109", "Huyện Phong Thổ", "Huyện", "12"),
                new District("110", "Huyện Than Uyên", "Huyện", "12"),
                new District("111", "Huyện Tân Uyên", "Huyện", "12"),
                new District("112", "Huyện Nậm Nhùn", "Huyện", "12"),
                new District("116", "Thành phố Sơn La", "Thành phố", "14"),
                new District("118", "Huyện Quỳnh Nhai", "Huyện", "14"),
                new District("119", "Huyện Thuận Châu", "Huyện", "14"),
                new District("120", "Huyện Mường La", "Huyện", "14"),
                new District("121", "Huyện Bắc Yên", "Huyện", "14"),
                new District("122", "Huyện Phù Yên", "Huyện", "14"),
                new District("123", "Huyện Mộc Châu", "Huyện", "14"),
                new District("124", "Huyện Yên Châu", "Huyện", "14"),
                new District("125", "Huyện Mai Sơn", "Huyện", "14"),
                new District("126", "Huyện Sông Mã", "Huyện", "14"),
                new District("127", "Huyện Sốp Cộp", "Huyện", "14"),
                new District("128", "Huyện Vân Hồ", "Huyện", "14"),
                new District("132", "Thành phố Yên Bái", "Thành phố", "15"),
                new District("133", "Thị xã Nghĩa Lộ", "Thị xã", "15"),
                new District("135", "Huyện Lục Yên", "Huyện", "15"),
                new District("136", "Huyện Văn Yên", "Huyện", "15"),
                new District("137", "Huyện Mù Căng Chải", "Huyện", "15"),
                new District("138", "Huyện Trấn Yên", "Huyện", "15"),
                new District("139", "Huyện Trạm Tấu", "Huyện", "15"),
                new District("140", "Huyện Văn Chấn", "Huyện", "15"),
                new District("141", "Huyện Yên Bình", "Huyện", "15"),
                new District("148", "Thành phố Hòa Bình", "Thành phố", "17"),
                new District("150", "Huyện Đà Bắc", "Huyện", "17"),
                new District("151", "Huyện Kỳ Sơn", "Huyện", "17"),
                new District("152", "Huyện Lương Sơn", "Huyện", "17"),
                new District("153", "Huyện Kim Bôi", "Huyện", "17"),
                new District("154", "Huyện Cao Phong", "Huyện", "17"),
                new District("155", "Huyện Tân Lạc", "Huyện", "17"),
                new District("156", "Huyện Mai Châu", "Huyện", "17"),
                new District("157", "Huyện Lạc Sơn", "Huyện", "17"),
                new District("158", "Huyện Yên Thủy", "Huyện", "17"),
                new District("159", "Huyện Lạc Thủy", "Huyện", "17"),
                new District("164", "Thành phố Thái Nguyên", "Thành phố", "19"),
                new District("165", "Thành phố Sông Công", "Thành phố", "19"),
                new District("167", "Huyện Định Hóa", "Huyện", "19"),
                new District("168", "Huyện Phú Lương", "Huyện", "19"),
                new District("169", "Huyện Đồng Hỷ", "Huyện", "19"),
                new District("170", "Huyện Võ Nhai", "Huyện", "19"),
                new District("171", "Huyện Đại Từ", "Huyện", "19"),
                new District("172", "Thị xã Phổ Yên", "Thị xã", "19"),
                new District("173", "Huyện Phú Bình", "Huyện", "19"),
                new District("178", "Thành phố Lạng Sơn", "Thành phố", "20"),
                new District("180", "Huyện Tràng Định", "Huyện", "20"),
                new District("181", "Huyện Bình Gia", "Huyện", "20"),
                new District("182", "Huyện Văn Lãng", "Huyện", "20"),
                new District("183", "Huyện Cao Lộc", "Huyện", "20"),
                new District("184", "Huyện Văn Quan", "Huyện", "20"),
                new District("185", "Huyện Bắc Sơn", "Huyện", "20"),
                new District("186", "Huyện Hữu Lũng", "Huyện", "20"),
                new District("187", "Huyện Chi Lăng", "Huyện", "20"),
                new District("188", "Huyện Lộc Bình", "Huyện", "20"),
                new District("189", "Huyện Đình Lập", "Huyện", "20"),
                new District("193", "Thành phố Hạ Long", "Thành phố", "22"),
                new District("194", "Thành phố Móng Cái", "Thành phố", "22"),
                new District("195", "Thành phố Cẩm Phả", "Thành phố", "22"),
                new District("196", "Thành phố Uông Bí", "Thành phố", "22"),
                new District("198", "Huyện Bình Liêu", "Huyện", "22"),
                new District("199", "Huyện Tiên Yên", "Huyện", "22"),
                new District("200", "Huyện Đầm Hà", "Huyện", "22"),
                new District("201", "Huyện Hải Hà", "Huyện", "22"),
                new District("202", "Huyện Ba Chẽ", "Huyện", "22"),
                new District("203", "Huyện Vân Đồn", "Huyện", "22"),
                new District("204", "Huyện Hoành Bồ", "Huyện", "22"),
                new District("205", "Thị xã Đông Triều", "Thị xã", "22"),
                new District("206", "Thị xã Quảng Yên", "Thị xã", "22"),
                new District("207", "Huyện Cô Tô", "Huyện", "22"),
                new District("213", "Thành phố Bắc Giang", "Thành phố", "24"),
                new District("215", "Huyện Yên Thế", "Huyện", "24"),
                new District("216", "Huyện Tân Yên", "Huyện", "24"),
                new District("217", "Huyện Lạng Giang", "Huyện", "24"),
                new District("218", "Huyện Lục Nam", "Huyện", "24"),
                new District("219", "Huyện Lục Ngạn", "Huyện", "24"),
                new District("220", "Huyện Sơn Động", "Huyện", "24"),
                new District("221", "Huyện Yên Dũng", "Huyện", "24"),
                new District("222", "Huyện Việt Yên", "Huyện", "24"),
                new District("223", "Huyện Hiệp Hòa", "Huyện", "24"),
                new District("227", "Thành phố Việt Trì", "Thành phố", "25"),
                new District("228", "Thị xã Phú Thọ", "Thị xã", "25"),
                new District("230", "Huyện Đoan Hùng", "Huyện", "25"),
                new District("231", "Huyện Hạ Hoà", "Huyện", "25"),
                new District("232", "Huyện Thanh Ba", "Huyện", "25"),
                new District("233", "Huyện Phù Ninh", "Huyện", "25"),
                new District("234", "Huyện Yên Lập", "Huyện", "25"),
                new District("235", "Huyện Cẩm Khê", "Huyện", "25"),
                new District("236", "Huyện Tam Nông", "Huyện", "25"),
                new District("237", "Huyện Lâm Thao", "Huyện", "25"),
                new District("238", "Huyện Thanh Sơn", "Huyện", "25"),
                new District("239", "Huyện Thanh Thuỷ", "Huyện", "25"),
                new District("240", "Huyện Tân Sơn", "Huyện", "25"),
                new District("243", "Thành phố Vĩnh Yên", "Thành phố", "26"),
                new District("244", "Thị xã Phúc Yên", "Thị xã", "26"),
                new District("246", "Huyện Lập Thạch", "Huyện", "26"),
                new District("247", "Huyện Tam Dương", "Huyện", "26"),
                new District("248", "Huyện Tam Đảo", "Huyện", "26"),
                new District("249", "Huyện Bình Xuyên", "Huyện", "26"),
                new District("250", "Huyện Mê Linh", "Huyện", "01"),
                new District("251", "Huyện Yên Lạc", "Huyện", "26"),
                new District("252", "Huyện Vĩnh Tường", "Huyện", "26"),
                new District("253", "Huyện Sông Lô", "Huyện", "26"),
                new District("256", "Thành phố Bắc Ninh", "Thành phố", "27"),
                new District("258", "Huyện Yên Phong", "Huyện", "27"),
                new District("259", "Huyện Quế Võ", "Huyện", "27"),
                new District("260", "Huyện Tiên Du", "Huyện", "27"),
                new District("261", "Thị xã Từ Sơn", "Thị xã", "27"),
                new District("262", "Huyện Thuận Thành", "Huyện", "27"),
                new District("263", "Huyện Gia Bình", "Huyện", "27"),
                new District("264", "Huyện Lương Tài", "Huyện", "27"),
                new District("268", "Quận Hà Đông", "Quận", "01"),
                new District("269", "Thị xã Sơn Tây", "Thị xã", "01"),
                new District("271", "Huyện Ba Vì", "Huyện", "01"),
                new District("272", "Huyện Phúc Thọ", "Huyện", "01"),
                new District("273", "Huyện Đan Phượng", "Huyện", "01"),
                new District("274", "Huyện Hoài Đức", "Huyện", "01"),
                new District("275", "Huyện Quốc Oai", "Huyện", "01"),
                new District("276", "Huyện Thạch Thất", "Huyện", "01"),
                new District("277", "Huyện Chương Mỹ", "Huyện", "01"),
                new District("278", "Huyện Thanh Oai", "Huyện", "01"),
                new District("279", "Huyện Thường Tín", "Huyện", "01"),
                new District("280", "Huyện Phú Xuyên", "Huyện", "01"),
                new District("281", "Huyện Ứng Hòa", "Huyện", "01"),
                new District("282", "Huyện Mỹ Đức", "Huyện", "01"),
                new District("288", "Thành phố Hải Dương", "Thành phố", "30"),
                new District("290", "Thị xã Chí Linh", "Thị xã", "30"),
                new District("291", "Huyện Nam Sách", "Huyện", "30"),
                new District("292", "Huyện Kinh Môn", "Huyện", "30"),
                new District("293", "Huyện Kim Thành", "Huyện", "30"),
                new District("294", "Huyện Thanh Hà", "Huyện", "30"),
                new District("295", "Huyện Cẩm Giàng", "Huyện", "30"),
                new District("296", "Huyện Bình Giang", "Huyện", "30"),
                new District("297", "Huyện Gia Lộc", "Huyện", "30"),
                new District("298", "Huyện Tứ Kỳ", "Huyện", "30"),
                new District("299", "Huyện Ninh Giang", "Huyện", "30"),
                new District("300", "Huyện Thanh Miện", "Huyện", "30"),
                new District("303", "Quận Hồng Bàng", "Quận", "31"),
                new District("304", "Quận Ngô Quyền", "Quận", "31"),
                new District("305", "Quận Lê Chân", "Quận", "31"),
                new District("306", "Quận Hải An", "Quận", "31"),
                new District("307", "Quận Kiến An", "Quận", "31"),
                new District("308", "Quận Đồ Sơn", "Quận", "31"),
                new District("309", "Quận Dương Kinh", "Quận", "31"),
                new District("311", "Huyện Thuỷ Nguyên", "Huyện", "31"),
                new District("312", "Huyện An Dương", "Huyện", "31"),
                new District("313", "Huyện An Lão", "Huyện", "31"),
                new District("314", "Huyện Kiến Thuỵ", "Huyện", "31"),
                new District("315", "Huyện Tiên Lãng", "Huyện", "31"),
                new District("316", "Huyện Vĩnh Bảo", "Huyện", "31"),
                new District("317", "Huyện Cát Hải", "Huyện", "31"),
                new District("318", "Huyện Bạch Long Vĩ", "Huyện", "31"),
                new District("323", "Thành phố Hưng Yên", "Thành phố", "33"),
                new District("325", "Huyện Văn Lâm", "Huyện", "33"),
                new District("326", "Huyện Văn Giang", "Huyện", "33"),
                new District("327", "Huyện Yên Mỹ", "Huyện", "33"),
                new District("328", "Huyện Mỹ Hào", "Huyện", "33"),
                new District("329", "Huyện Ân Thi", "Huyện", "33"),
                new District("330", "Huyện Khoái Châu", "Huyện", "33"),
                new District("331", "Huyện Kim Động", "Huyện", "33"),
                new District("332", "Huyện Tiên Lữ", "Huyện", "33"),
                new District("333", "Huyện Phù Cừ", "Huyện", "33"),
                new District("336", "Thành phố Thái Bình", "Thành phố", "34"),
                new District("338", "Huyện Quỳnh Phụ", "Huyện", "34"),
                new District("339", "Huyện Hưng Hà", "Huyện", "34"),
                new District("340", "Huyện Đông Hưng", "Huyện", "34"),
                new District("341", "Huyện Thái Thụy", "Huyện", "34"),
                new District("342", "Huyện Tiền Hải", "Huyện", "34"),
                new District("343", "Huyện Kiến Xương", "Huyện", "34"),
                new District("344", "Huyện Vũ Thư", "Huyện", "34"),
                new District("347", "Thành phố Phủ Lý", "Thành phố", "35"),
                new District("349", "Huyện Duy Tiên", "Huyện", "35"),
                new District("350", "Huyện Kim Bảng", "Huyện", "35"),
                new District("351", "Huyện Thanh Liêm", "Huyện", "35"),
                new District("352", "Huyện Bình Lục", "Huyện", "35"),
                new District("353", "Huyện Lý Nhân", "Huyện", "35"),
                new District("356", "Thành phố Nam Định", "Thành phố", "36"),
                new District("358", "Huyện Mỹ Lộc", "Huyện", "36"),
                new District("359", "Huyện Vụ Bản", "Huyện", "36"),
                new District("360", "Huyện Ý Yên", "Huyện", "36"),
                new District("361", "Huyện Nghĩa Hưng", "Huyện", "36"),
                new District("362", "Huyện Nam Trực", "Huyện", "36"),
                new District("363", "Huyện Trực Ninh", "Huyện", "36"),
                new District("364", "Huyện Xuân Trường", "Huyện", "36"),
                new District("365", "Huyện Giao Thủy", "Huyện", "36"),
                new District("366", "Huyện Hải Hậu", "Huyện", "36"),
                new District("369", "Thành phố Ninh Bình", "Thành phố", "37"),
                new District("370", "Thành phố Tam Điệp", "Thành phố", "37"),
                new District("372", "Huyện Nho Quan", "Huyện", "37"),
                new District("373", "Huyện Gia Viễn", "Huyện", "37"),
                new District("374", "Huyện Hoa Lư", "Huyện", "37"),
                new District("375", "Huyện Yên Khánh", "Huyện", "37"),
                new District("376", "Huyện Kim Sơn", "Huyện", "37"),
                new District("377", "Huyện Yên Mô", "Huyện", "37"),
                new District("380", "Thành phố Thanh Hóa", "Thành phố", "38"),
                new District("381", "Thị xã Bỉm Sơn", "Thị xã", "38"),
                new District("382", "Thị xã Sầm Sơn", "Thị xã", "38"),
                new District("384", "Huyện Mường Lát", "Huyện", "38"),
                new District("385", "Huyện Quan Hóa", "Huyện", "38"),
                new District("386", "Huyện Bá Thước", "Huyện", "38"),
                new District("387", "Huyện Quan Sơn", "Huyện", "38"),
                new District("388", "Huyện Lang Chánh", "Huyện", "38"),
                new District("389", "Huyện Ngọc Lặc", "Huyện", "38"),
                new District("390", "Huyện Cẩm Thủy", "Huyện", "38"),
                new District("391", "Huyện Thạch Thành", "Huyện", "38"),
                new District("392", "Huyện Hà Trung", "Huyện", "38"),
                new District("393", "Huyện Vĩnh Lộc", "Huyện", "38"),
                new District("394", "Huyện Yên Định", "Huyện", "38"),
                new District("395", "Huyện Thọ Xuân", "Huyện", "38"),
                new District("396", "Huyện Thường Xuân", "Huyện", "38"),
                new District("397", "Huyện Triệu Sơn", "Huyện", "38"),
                new District("398", "Huyện Thiệu Hóa", "Huyện", "38"),
                new District("399", "Huyện Hoằng Hóa", "Huyện", "38"),
                new District("400", "Huyện Hậu Lộc", "Huyện", "38"),
                new District("401", "Huyện Nga Sơn", "Huyện", "38"),
                new District("402", "Huyện Như Xuân", "Huyện", "38"),
                new District("403", "Huyện Như Thanh", "Huyện", "38"),
                new District("404", "Huyện Nông Cống", "Huyện", "38"),
                new District("405", "Huyện Đông Sơn", "Huyện", "38"),
                new District("406", "Huyện Quảng Xương", "Huyện", "38"),
                new District("407", "Huyện Tĩnh Gia", "Huyện", "38"),
                new District("412", "Thành phố Vinh", "Thành phố", "40"),
                new District("413", "Thị xã Cửa Lò", "Thị xã", "40"),
                new District("414", "Thị xã Thái Hoà", "Thị xã", "40"),
                new District("415", "Huyện Quế Phong", "Huyện", "40"),
                new District("416", "Huyện Quỳ Châu", "Huyện", "40"),
                new District("417", "Huyện Kỳ Sơn", "Huyện", "40"),
                new District("418", "Huyện Tương Dương", "Huyện", "40"),
                new District("419", "Huyện Nghĩa Đàn", "Huyện", "40"),
                new District("420", "Huyện Quỳ Hợp", "Huyện", "40"),
                new District("421", "Huyện Quỳnh Lưu", "Huyện", "40"),
                new District("422", "Huyện Con Cuông", "Huyện", "40"),
                new District("423", "Huyện Tân Kỳ", "Huyện", "40"),
                new District("424", "Huyện Anh Sơn", "Huyện", "40"),
                new District("425", "Huyện Diễn Châu", "Huyện", "40"),
                new District("426", "Huyện Yên Thành", "Huyện", "40"),
                new District("427", "Huyện Đô Lương", "Huyện", "40"),
                new District("428", "Huyện Thanh Chương", "Huyện", "40"),
                new District("429", "Huyện Nghi Lộc", "Huyện", "40"),
                new District("430", "Huyện Nam Đàn", "Huyện", "40"),
                new District("431", "Huyện Hưng Nguyên", "Huyện", "40"),
                new District("432", "Thị xã Hoàng Mai", "Thị xã", "40"),
                new District("436", "Thành phố Hà Tĩnh", "Thành phố", "42"),
                new District("437", "Thị xã Hồng Lĩnh", "Thị xã", "42"),
                new District("439", "Huyện Hương Sơn", "Huyện", "42"),
                new District("440", "Huyện Đức Thọ", "Huyện", "42"),
                new District("441", "Huyện Vũ Quang", "Huyện", "42"),
                new District("442", "Huyện Nghi Xuân", "Huyện", "42"),
                new District("443", "Huyện Can Lộc", "Huyện", "42"),
                new District("444", "Huyện Hương Khê", "Huyện", "42"),
                new District("445", "Huyện Thạch Hà", "Huyện", "42"),
                new District("446", "Huyện Cẩm Xuyên", "Huyện", "42"),
                new District("447", "Huyện Kỳ Anh", "Huyện", "42"),
                new District("448", "Huyện Lộc Hà", "Huyện", "42"),
                new District("449", "Thị xã Kỳ Anh", "Thị xã", "42"),
                new District("450", "Thành Phố Đồng Hới", "Thành phố", "44"),
                new District("452", "Huyện Minh Hóa", "Huyện", "44"),
                new District("453", "Huyện Tuyên Hóa", "Huyện", "44"),
                new District("454", "Huyện Quảng Trạch", "Thị xã", "44"),
                new District("455", "Huyện Bố Trạch", "Huyện", "44"),
                new District("456", "Huyện Quảng Ninh", "Huyện", "44"),
                new District("457", "Huyện Lệ Thủy", "Huyện", "44"),
                new District("458", "Thị xã Ba Đồn", "Huyện", "44"),
                new District("461", "Thành phố Đông Hà", "Thành phố", "45"),
                new District("462", "Thị xã Quảng Trị", "Thị xã", "45"),
                new District("464", "Huyện Vĩnh Linh", "Huyện", "45"),
                new District("465", "Huyện Hướng Hóa", "Huyện", "45"),
                new District("466", "Huyện Gio Linh", "Huyện", "45"),
                new District("467", "Huyện Đa Krông", "Huyện", "45"),
                new District("468", "Huyện Cam Lộ", "Huyện", "45"),
                new District("469", "Huyện Triệu Phong", "Huyện", "45"),
                new District("470", "Huyện Hải Lăng", "Huyện", "45"),
                new District("471", "Huyện Cồn Cỏ", "Huyện", "45"),
                new District("474", "Thành phố Huế", "Thành phố", "46"),
                new District("476", "Huyện Phong Điền", "Huyện", "46"),
                new District("477", "Huyện Quảng Điền", "Huyện", "46"),
                new District("478", "Huyện Phú Vang", "Huyện", "46"),
                new District("479", "Thị xã Hương Thủy", "Thị xã", "46"),
                new District("480", "Thị xã Hương Trà", "Thị xã", "46"),
                new District("481", "Huyện A Lưới", "Huyện", "46"),
                new District("482", "Huyện Phú Lộc", "Huyện", "46"),
                new District("483", "Huyện Nam Đông", "Huyện", "46"),
                new District("490", "Quận Liên Chiểu", "Quận", "48"),
                new District("491", "Quận Thanh Khê", "Quận", "48"),
                new District("492", "Quận Hải Châu", "Quận", "48"),
                new District("493", "Quận Sơn Trà", "Quận", "48"),
                new District("494", "Quận Ngũ Hành Sơn", "Quận", "48"),
                new District("495", "Quận Cẩm Lệ", "Quận", "48"),
                new District("497", "Huyện Hòa Vang", "Huyện", "48"),
                new District("498", "Huyện Hoàng Sa", "Huyện", "48"),
                new District("502", "Thành phố Tam Kỳ", "Thành phố", "49"),
                new District("503", "Thành phố Hội An", "Thành phố", "49"),
                new District("504", "Huyện Tây Giang", "Huyện", "49"),
                new District("505", "Huyện Đông Giang", "Huyện", "49"),
                new District("506", "Huyện Đại Lộc", "Huyện", "49"),
                new District("507", "Thị xã Điện Bàn", "Thị xã", "49"),
                new District("508", "Huyện Duy Xuyên", "Huyện", "49"),
                new District("509", "Huyện Quế Sơn", "Huyện", "49"),
                new District("510", "Huyện Nam Giang", "Huyện", "49"),
                new District("511", "Huyện Phước Sơn", "Huyện", "49"),
                new District("512", "Huyện Hiệp Đức", "Huyện", "49"),
                new District("513", "Huyện Thăng Bình", "Huyện", "49"),
                new District("514", "Huyện Tiên Phước", "Huyện", "49"),
                new District("515", "Huyện Bắc Trà My", "Huyện", "49"),
                new District("516", "Huyện Nam Trà My", "Huyện", "49"),
                new District("517", "Huyện Núi Thành", "Huyện", "49"),
                new District("518", "Huyện Phú Ninh", "Huyện", "49"),
                new District("519", "Huyện Nông Sơn", "Huyện", "49"),
                new District("522", "Thành phố Quảng Ngãi", "Thành phố", "51"),
                new District("524", "Huyện Bình Sơn", "Huyện", "51"),
                new District("525", "Huyện Trà Bồng", "Huyện", "51"),
                new District("526", "Huyện Tây Trà", "Huyện", "51"),
                new District("527", "Huyện Sơn Tịnh", "Huyện", "51"),
                new District("528", "Huyện Tư Nghĩa", "Huyện", "51"),
                new District("529", "Huyện Sơn Hà", "Huyện", "51"),
                new District("530", "Huyện Sơn Tây", "Huyện", "51"),
                new District("531", "Huyện Minh Long", "Huyện", "51"),
                new District("532", "Huyện Nghĩa Hành", "Huyện", "51"),
                new District("533", "Huyện Mộ Đức", "Huyện", "51"),
                new District("534", "Huyện Đức Phổ", "Huyện", "51"),
                new District("535", "Huyện Ba Tơ", "Huyện", "51"),
                new District("536", "Huyện Lý Sơn", "Huyện", "51"),
                new District("540", "Thành phố Qui Nhơn", "Thành phố", "52"),
                new District("542", "Huyện An Lão", "Huyện", "52"),
                new District("543", "Huyện Hoài Nhơn", "Huyện", "52"),
                new District("544", "Huyện Hoài Ân", "Huyện", "52"),
                new District("545", "Huyện Phù Mỹ", "Huyện", "52"),
                new District("546", "Huyện Vĩnh Thạnh", "Huyện", "52"),
                new District("547", "Huyện Tây Sơn", "Huyện", "52"),
                new District("548", "Huyện Phù Cát", "Huyện", "52"),
                new District("549", "Thị xã An Nhơn", "Thị xã", "52"),
                new District("550", "Huyện Tuy Phước", "Huyện", "52"),
                new District("551", "Huyện Vân Canh", "Huyện", "52"),
                new District("555", "Thành phố Tuy Hoà", "Thành phố", "54"),
                new District("557", "Thị xã Sông Cầu", "Thị xã", "54"),
                new District("558", "Huyện Đồng Xuân", "Huyện", "54"),
                new District("559", "Huyện Tuy An", "Huyện", "54"),
                new District("560", "Huyện Sơn Hòa", "Huyện", "54"),
                new District("561", "Huyện Sông Hinh", "Huyện", "54"),
                new District("562", "Huyện Tây Hoà", "Huyện", "54"),
                new District("563", "Huyện Phú Hoà", "Huyện", "54"),
                new District("564", "Huyện Đông Hòa", "Huyện", "54"),
                new District("568", "Thành phố Nha Trang", "Thành phố", "56"),
                new District("569", "Thành phố Cam Ranh", "Thành phố", "56"),
                new District("570", "Huyện Cam Lâm", "Huyện", "56"),
                new District("571", "Huyện Vạn Ninh", "Huyện", "56"),
                new District("572", "Thị xã Ninh Hòa", "Thị xã", "56"),
                new District("573", "Huyện Khánh Vĩnh", "Huyện", "56"),
                new District("574", "Huyện Diên Khánh", "Huyện", "56"),
                new District("575", "Huyện Khánh Sơn", "Huyện", "56"),
                new District("576", "Huyện Trường Sa", "Huyện", "56"),
                new District("582", "Thành phố Phan Rang-Tháp Chàm", "Thành phố", "58"),
                new District("584", "Huyện Bác Ái", "Huyện", "58"),
                new District("585", "Huyện Ninh Sơn", "Huyện", "58"),
                new District("586", "Huyện Ninh Hải", "Huyện", "58"),
                new District("587", "Huyện Ninh Phước", "Huyện", "58"),
                new District("588", "Huyện Thuận Bắc", "Huyện", "58"),
                new District("589", "Huyện Thuận Nam", "Huyện", "58"),
                new District("593", "Thành phố Phan Thiết", "Thành phố", "60"),
                new District("594", "Thị xã La Gi", "Thị xã", "60"),
                new District("595", "Huyện Tuy Phong", "Huyện", "60"),
                new District("596", "Huyện Bắc Bình", "Huyện", "60"),
                new District("597", "Huyện Hàm Thuận Bắc", "Huyện", "60"),
                new District("598", "Huyện Hàm Thuận Nam", "Huyện", "60"),
                new District("599", "Huyện Tánh Linh", "Huyện", "60"),
                new District("600", "Huyện Đức Linh", "Huyện", "60"),
                new District("601", "Huyện Hàm Tân", "Huyện", "60"),
                new District("602", "Huyện Phú Quí", "Huyện", "60"),
                new District("608", "Thành phố Kon Tum", "Thành phố", "62"),
                new District("610", "Huyện Đắk Glei", "Huyện", "62"),
                new District("611", "Huyện Ngọc Hồi", "Huyện", "62"),
                new District("612", "Huyện Đắk Tô", "Huyện", "62"),
                new District("613", "Huyện Kon Plông", "Huyện", "62"),
                new District("614", "Huyện Kon Rẫy", "Huyện", "62"),
                new District("615", "Huyện Đắk Hà", "Huyện", "62"),
                new District("616", "Huyện Sa Thầy", "Huyện", "62"),
                new District("617", "Huyện Tu Mơ Rông", "Huyện", "62"),
                new District("618", "Huyện Ia H&lsquo;Drai", "Huyện", "62"),
                new District("622", "Thành phố Pleiku", "Thành phố", "64"),
                new District("623", "Thị xã An Khê", "Thị xã", "64"),
                new District("624", "Thị xã Ayun Pa", "Thị xã", "64"),
                new District("625", "Huyện KBang", "Huyện", "64"),
                new District("626", "Huyện Đăk Đoa", "Huyện", "64"),
                new District("627", "Huyện Chư Păh", "Huyện", "64"),
                new District("628", "Huyện Ia Grai", "Huyện", "64"),
                new District("629", "Huyện Mang Yang", "Huyện", "64"),
                new District("630", "Huyện Kông Chro", "Huyện", "64"),
                new District("631", "Huyện Đức Cơ", "Huyện", "64"),
                new District("632", "Huyện Chư Prông", "Huyện", "64"),
                new District("633", "Huyện Chư Sê", "Huyện", "64"),
                new District("634", "Huyện Đăk Pơ", "Huyện", "64"),
                new District("635", "Huyện Ia Pa", "Huyện", "64"),
                new District("637", "Huyện Krông Pa", "Huyện", "64"),
                new District("638", "Huyện Phú Thiện", "Huyện", "64"),
                new District("639", "Huyện Chư Pưh", "Huyện", "64"),
                new District("643", "Thành phố Buôn Ma Thuột", "Thành phố", "66"),
                new District("644", "Thị Xã Buôn Hồ", "Thị xã", "66"),
                new District("645", "Huyện Ea H&lsquo;leo", "Huyện", "66"),
                new District("646", "Huyện Ea Súp", "Huyện", "66"),
                new District("647", "Huyện Buôn Đôn", "Huyện", "66"),
                new District("648", "Huyện Cư M&lsquo;gar", "Huyện", "66"),
                new District("649", "Huyện Krông Búk", "Huyện", "66"),
                new District("650", "Huyện Krông Năng", "Huyện", "66"),
                new District("651", "Huyện Ea Kar", "Huyện", "66"),
                new District("652", "Huyện M&lsquo;Đrắk", "Huyện", "66"),
                new District("653", "Huyện Krông Bông", "Huyện", "66"),
                new District("654", "Huyện Krông Pắc", "Huyện", "66"),
                new District("655", "Huyện Krông A Na", "Huyện", "66"),
                new District("656", "Huyện Lắk", "Huyện", "66"),
                new District("657", "Huyện Cư Kuin", "Huyện", "66"),
                new District("660", "Thị xã Gia Nghĩa", "Thị xã", "67"),
                new District("661", "Huyện Đăk Glong", "Huyện", "67"),
                new District("662", "Huyện Cư Jút", "Huyện", "67"),
                new District("663", "Huyện Đắk Mil", "Huyện", "67"),
                new District("664", "Huyện Krông Nô", "Huyện", "67"),
                new District("665", "Huyện Đắk Song", "Huyện", "67"),
                new District("666", "Huyện Đắk R&lsquo;Lấp", "Huyện", "67"),
                new District("667", "Huyện Tuy Đức", "Huyện", "67"),
                new District("672", "Thành phố Đà Lạt", "Thành phố", "68"),
                new District("673", "Thành phố Bảo Lộc", "Thành phố", "68"),
                new District("674", "Huyện Đam Rông", "Huyện", "68"),
                new District("675", "Huyện Lạc Dương", "Huyện", "68"),
                new District("676", "Huyện Lâm Hà", "Huyện", "68"),
                new District("677", "Huyện Đơn Dương", "Huyện", "68"),
                new District("678", "Huyện Đức Trọng", "Huyện", "68"),
                new District("679", "Huyện Di Linh", "Huyện", "68"),
                new District("680", "Huyện Bảo Lâm", "Huyện", "68"),
                new District("681", "Huyện Đạ Huoai", "Huyện", "68"),
                new District("682", "Huyện Đạ Tẻh", "Huyện", "68"),
                new District("683", "Huyện Cát Tiên", "Huyện", "68"),
                new District("688", "Thị xã Phước Long", "Thị xã", "70"),
                new District("689", "Thị xã Đồng Xoài", "Thị xã", "70"),
                new District("690", "Thị xã Bình Long", "Thị xã", "70"),
                new District("691", "Huyện Bù Gia Mập", "Huyện", "70"),
                new District("692", "Huyện Lộc Ninh", "Huyện", "70"),
                new District("693", "Huyện Bù Đốp", "Huyện", "70"),
                new District("694", "Huyện Hớn Quản", "Huyện", "70"),
                new District("695", "Huyện Đồng Phú", "Huyện", "70"),
                new District("696", "Huyện Bù Đăng", "Huyện", "70"),
                new District("697", "Huyện Chơn Thành", "Huyện", "70"),
                new District("698", "Huyện Phú Riềng", "Huyện", "70"),
                new District("703", "Thành phố Tây Ninh", "Thành phố", "72"),
                new District("705", "Huyện Tân Biên", "Huyện", "72"),
                new District("706", "Huyện Tân Châu", "Huyện", "72"),
                new District("707", "Huyện Dương Minh Châu", "Huyện", "72"),
                new District("708", "Huyện Châu Thành", "Huyện", "72"),
                new District("709", "Huyện Hòa Thành", "Huyện", "72"),
                new District("710", "Huyện Gò Dầu", "Huyện", "72"),
                new District("711", "Huyện Bến Cầu", "Huyện", "72"),
                new District("712", "Huyện Trảng Bàng", "Huyện", "72"),
                new District("718", "Thành phố Thủ Dầu Một", "Thành phố", "74"),
                new District("719", "Huyện Bàu Bàng", "Huyện", "74"),
                new District("720", "Huyện Dầu Tiếng", "Huyện", "74"),
                new District("721", "Thị xã Bến Cát", "Thị xã", "74"),
                new District("722", "Huyện Phú Giáo", "Huyện", "74"),
                new District("723", "Thị xã Tân Uyên", "Thị xã", "74"),
                new District("724", "Thị xã Dĩ An", "Thị xã", "74"),
                new District("725", "Thị xã Thuận An", "Thị xã", "74"),
                new District("726", "Huyện Bắc Tân Uyên", "Huyện", "74"),
                new District("731", "Thành phố Biên Hòa", "Thành phố", "75"),
                new District("732", "Thị xã Long Khánh", "Thị xã", "75"),
                new District("734", "Huyện Tân Phú", "Huyện", "75"),
                new District("735", "Huyện Vĩnh Cửu", "Huyện", "75"),
                new District("736", "Huyện Định Quán", "Huyện", "75"),
                new District("737", "Huyện Trảng Bom", "Huyện", "75"),
                new District("738", "Huyện Thống Nhất", "Huyện", "75"),
                new District("739", "Huyện Cẩm Mỹ", "Huyện", "75"),
                new District("740", "Huyện Long Thành", "Huyện", "75"),
                new District("741", "Huyện Xuân Lộc", "Huyện", "75"),
                new District("742", "Huyện Nhơn Trạch", "Huyện", "75"),
                new District("747", "Thành phố Vũng Tàu", "Thành phố", "77"),
                new District("748", "Thành phố Bà Rịa", "Thành phố", "77"),
                new District("750", "Huyện Châu Đức", "Huyện", "77"),
                new District("751", "Huyện Xuyên Mộc", "Huyện", "77"),
                new District("752", "Huyện Long Điền", "Huyện", "77"),
                new District("753", "Huyện Đất Đỏ", "Huyện", "77"),
                new District("754", "Huyện Tân Thành", "Huyện", "77"),
                new District("755", "Huyện Côn Đảo", "Huyện", "77"),
                new District("760", "Quận 1", "Quận", "79"),
                new District("761", "Quận 12", "Quận", "79"),
                new District("762", "Quận Thủ Đức", "Quận", "79"),
                new District("763", "Quận 9", "Quận", "79"),
                new District("764", "Quận Gò Vấp", "Quận", "79"),
                new District("765", "Quận Bình Thạnh", "Quận", "79"),
                new District("766", "Quận Tân Bình", "Quận", "79"),
                new District("767", "Quận Tân Phú", "Quận", "79"),
                new District("768", "Quận Phú Nhuận", "Quận", "79"),
                new District("769", "Quận 2", "Quận", "79"),
                new District("770", "Quận 3", "Quận", "79"),
                new District("771", "Quận 10", "Quận", "79"),
                new District("772", "Quận 11", "Quận", "79"),
                new District("773", "Quận 4", "Quận", "79"),
                new District("774", "Quận 5", "Quận", "79"),
                new District("775", "Quận 6", "Quận", "79"),
                new District("776", "Quận 8", "Quận", "79"),
                new District("777", "Quận Bình Tân", "Quận", "79"),
                new District("778", "Quận 7", "Quận", "79"),
                new District("783", "Huyện Củ Chi", "Huyện", "79"),
                new District("784", "Huyện Hóc Môn", "Huyện", "79"),
                new District("785", "Huyện Bình Chánh", "Huyện", "79"),
                new District("786", "Huyện Nhà Bè", "Huyện", "79"),
                new District("787", "Huyện Cần Giờ", "Huyện", "79"),
                new District("794", "Thành phố Tân An", "Thành phố", "80"),
                new District("795", "Thị xã Kiến Tường", "Thị xã", "80"),
                new District("796", "Huyện Tân Hưng", "Huyện", "80"),
                new District("797", "Huyện Vĩnh Hưng", "Huyện", "80"),
                new District("798", "Huyện Mộc Hóa", "Huyện", "80"),
                new District("799", "Huyện Tân Thạnh", "Huyện", "80"),
                new District("800", "Huyện Thạnh Hóa", "Huyện", "80"),
                new District("801", "Huyện Đức Huệ", "Huyện", "80"),
                new District("802", "Huyện Đức Hòa", "Huyện", "80"),
                new District("803", "Huyện Bến Lức", "Huyện", "80"),
                new District("804", "Huyện Thủ Thừa", "Huyện", "80"),
                new District("805", "Huyện Tân Trụ", "Huyện", "80"),
                new District("806", "Huyện Cần Đước", "Huyện", "80"),
                new District("807", "Huyện Cần Giuộc", "Huyện", "80"),
                new District("808", "Huyện Châu Thành", "Huyện", "80"),
                new District("815", "Thành phố Mỹ Tho", "Thành phố", "82"),
                new District("816", "Thị xã Gò Công", "Thị xã", "82"),
                new District("817", "Thị xã Cai Lậy", "Huyện", "82"),
                new District("818", "Huyện Tân Phước", "Huyện", "82"),
                new District("819", "Huyện Cái Bè", "Huyện", "82"),
                new District("820", "Huyện Cai Lậy", "Thị xã", "82"),
                new District("821", "Huyện Châu Thành", "Huyện", "82"),
                new District("822", "Huyện Chợ Gạo", "Huyện", "82"),
                new District("823", "Huyện Gò Công Tây", "Huyện", "82"),
                new District("824", "Huyện Gò Công Đông", "Huyện", "82"),
                new District("825", "Huyện Tân Phú Đông", "Huyện", "82"),
                new District("829", "Thành phố Bến Tre", "Thành phố", "83"),
                new District("831", "Huyện Châu Thành", "Huyện", "83"),
                new District("832", "Huyện Chợ Lách", "Huyện", "83"),
                new District("833", "Huyện Mỏ Cày Nam", "Huyện", "83"),
                new District("834", "Huyện Giồng Trôm", "Huyện", "83"),
                new District("835", "Huyện Bình Đại", "Huyện", "83"),
                new District("836", "Huyện Ba Tri", "Huyện", "83"),
                new District("837", "Huyện Thạnh Phú", "Huyện", "83"),
                new District("838", "Huyện Mỏ Cày Bắc", "Huyện", "83"),
                new District("842", "Thành phố Trà Vinh", "Thành phố", "84"),
                new District("844", "Huyện Càng Long", "Huyện", "84"),
                new District("845", "Huyện Cầu Kè", "Huyện", "84"),
                new District("846", "Huyện Tiểu Cần", "Huyện", "84"),
                new District("847", "Huyện Châu Thành", "Huyện", "84"),
                new District("848", "Huyện Cầu Ngang", "Huyện", "84"),
                new District("849", "Huyện Trà Cú", "Huyện", "84"),
                new District("850", "Huyện Duyên Hải", "Huyện", "84"),
                new District("851", "Thị xã Duyên Hải", "Thị xã", "84"),
                new District("855", "Thành phố Vĩnh Long", "Thành phố", "86"),
                new District("857", "Huyện Long Hồ", "Huyện", "86"),
                new District("858", "Huyện Mang Thít", "Huyện", "86"),
                new District("859", "Huyện  Vũng Liêm", "Huyện", "86"),
                new District("860", "Huyện Tam Bình", "Huyện", "86"),
                new District("861", "Thị xã Bình Minh", "Thị xã", "86"),
                new District("862", "Huyện Trà Ôn", "Huyện", "86"),
                new District("863", "Huyện Bình Tân", "Huyện", "86"),
                new District("866", "Thành phố Cao Lãnh", "Thành phố", "87"),
                new District("867", "Thành phố Sa Đéc", "Thành phố", "87"),
                new District("868", "Thị xã Hồng Ngự", "Thị xã", "87"),
                new District("869", "Huyện Tân Hồng", "Huyện", "87"),
                new District("870", "Huyện Hồng Ngự", "Huyện", "87"),
                new District("871", "Huyện Tam Nông", "Huyện", "87"),
                new District("872", "Huyện Tháp Mười", "Huyện", "87"),
                new District("873", "Huyện Cao Lãnh", "Huyện", "87"),
                new District("874", "Huyện Thanh Bình", "Huyện", "87"),
                new District("875", "Huyện Lấp Vò", "Huyện", "87"),
                new District("876", "Huyện Lai Vung", "Huyện", "87"),
                new District("877", "Huyện Châu Thành", "Huyện", "87"),
                new District("883", "Thành phố Long Xuyên", "Thành phố", "89"),
                new District("884", "Thành phố Châu Đốc", "Thành phố", "89"),
                new District("886", "Huyện An Phú", "Huyện", "89"),
                new District("887", "Thị xã Tân Châu", "Thị xã", "89"),
                new District("888", "Huyện Phú Tân", "Huyện", "89"),
                new District("889", "Huyện Châu Phú", "Huyện", "89"),
                new District("890", "Huyện Tịnh Biên", "Huyện", "89"),
                new District("891", "Huyện Tri Tôn", "Huyện", "89"),
                new District("892", "Huyện Châu Thành", "Huyện", "89"),
                new District("893", "Huyện Chợ Mới", "Huyện", "89"),
                new District("894", "Huyện Thoại Sơn", "Huyện", "89"),
                new District("899", "Thành phố Rạch Giá", "Thành phố", "91"),
                new District("900", "Thị xã Hà Tiên", "Thị xã", "91"),
                new District("902", "Huyện Kiên Lương", "Huyện", "91"),
                new District("903", "Huyện Hòn Đất", "Huyện", "91"),
                new District("904", "Huyện Tân Hiệp", "Huyện", "91"),
                new District("905", "Huyện Châu Thành", "Huyện", "91"),
                new District("906", "Huyện Giồng Riềng", "Huyện", "91"),
                new District("907", "Huyện Gò Quao", "Huyện", "91"),
                new District("908", "Huyện An Biên", "Huyện", "91"),
                new District("909", "Huyện An Minh", "Huyện", "91"),
                new District("910", "Huyện Vĩnh Thuận", "Huyện", "91"),
                new District("911", "Huyện Phú Quốc", "Huyện", "91"),
                new District("912", "Huyện Kiên Hải", "Huyện", "91"),
                new District("913", "Huyện U Minh Thượng", "Huyện", "91"),
                new District("914", "Huyện Giang Thành", "Huyện", "91"),
                new District("916", "Quận Ninh Kiều", "Quận", "92"),
                new District("917", "Quận Ô Môn", "Quận", "92"),
                new District("918", "Quận Bình Thuỷ", "Quận", "92"),
                new District("919", "Quận Cái Răng", "Quận", "92"),
                new District("923", "Quận Thốt Nốt", "Quận", "92"),
                new District("924", "Huyện Vĩnh Thạnh", "Huyện", "92"),
                new District("925", "Huyện Cờ Đỏ", "Huyện", "92"),
                new District("926", "Huyện Phong Điền", "Huyện", "92"),
                new District("927", "Huyện Thới Lai", "Huyện", "92"),
                new District("930", "Thành phố Vị Thanh", "Thành phố", "93"),
                new District("931", "Thị xã Ngã Bảy", "Thị xã", "93"),
                new District("932", "Huyện Châu Thành A", "Huyện", "93"),
                new District("933", "Huyện Châu Thành", "Huyện", "93"),
                new District("934", "Huyện Phụng Hiệp", "Huyện", "93"),
                new District("935", "Huyện Vị Thuỷ", "Huyện", "93"),
                new District("936", "Huyện Long Mỹ", "Huyện", "93"),
                new District("937", "Thị xã Long Mỹ", "Thị xã", "93"),
                new District("941", "Thành phố Sóc Trăng", "Thành phố", "94"),
                new District("942", "Huyện Châu Thành", "Huyện", "94"),
                new District("943", "Huyện Kế Sách", "Huyện", "94"),
                new District("944", "Huyện Mỹ Tú", "Huyện", "94"),
                new District("945", "Huyện Cù Lao Dung", "Huyện", "94"),
                new District("946", "Huyện Long Phú", "Huyện", "94"),
                new District("947", "Huyện Mỹ Xuyên", "Huyện", "94"),
                new District("948", "Thị xã Ngã Năm", "Thị xã", "94"),
                new District("949", "Huyện Thạnh Trị", "Huyện", "94"),
                new District("950", "Thị xã Vĩnh Châu", "Thị xã", "94"),
                new District("951", "Huyện Trần Đề", "Huyện", "94"),
                new District("954", "Thành phố Bạc Liêu", "Thành phố", "95"),
                new District("956", "Huyện Hồng Dân", "Huyện", "95"),
                new District("957", "Huyện Phước Long", "Huyện", "95"),
                new District("958", "Huyện Vĩnh Lợi", "Huyện", "95"),
                new District("959", "Thị xã Giá Rai", "Thị xã", "95"),
                new District("960", "Huyện Đông Hải", "Huyện", "95"),
                new District("961", "Huyện Hoà Bình", "Huyện", "95"),
                new District("964", "Thành phố Cà Mau", "Thành phố", "96"),
                new District("966", "Huyện U Minh", "Huyện", "96"),
                new District("967", "Huyện Thới Bình", "Huyện", "96"),
                new District("968", "Huyện Trần Văn Thời", "Huyện", "96"),
                new District("969", "Huyện Cái Nước", "Huyện", "96"),
                new District("970", "Huyện Đầm Dơi", "Huyện", "96"),
                new District("971", "Huyện Năm Căn", "Huyện", "96"),
                new District("972", "Huyện Phú Tân", "Huyện", "96"),
                new District("973", "Huyện Ngọc Hiển", "Huyện", "96"),

            };

        }
    }
}